services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: importtimporta-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=importtimporta;User=importt;Password=123456;SslMode=none;"
      Jwt__Key: "JWT_SECRET_AQUI"
      Jwt__Issuer: "api-importtimporta"
      Jwt__Audience: "api-importtimporta"
      AWS__Region: "us-east-1"
      AWS__AccessKey: "AWS_ACCESS_KEY"
      AWS__SecretKey: "AWS_SECRET_KEY"
      AWS__BucketName: "importtimporta"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_importt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: importtimporta
      MYSQL_USER: importt
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
